# Generated by Django 5.1 on 2024-09-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_created_on_remove_clients_deleted_on'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clients.clients'),
        ),
    ]
