# Generated by Django 5.1.1 on 2024-09-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='deleted_on',
        ),
    ]
