# Generated by Django 5.1 on 2024-09-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('expense_type', models.CharField(choices=[('judicial_fee', 'Custas processuais'), ('attorney_fee', 'Honorários advocatícios'), ('operational', 'Despesas operacionais'), ('third_party', 'Honorários de terceiros'), ('documentation', 'Taxas de documentação'), ('penalty', 'Multas ou penalidades'), ('notification', 'Notificações e intimações')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='processes.process')),
            ],
        ),
    ]
