# Generated by Django 5.1 on 2024-09-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compromisso',
            new_name='Commitment',
        ),
    ]
