# Generated by Django 5.1 on 2024-09-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_calendar', '0002_rename_compromisso_commitment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='criado_em',
            new_name='criated_in',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='data_hora_fim',
            new_name='date_time_end',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='data_hora_inicio',
            new_name='date_time_start',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='titulo',
            new_name='title',
        ),
    ]
