# Generated by Django 5.1 on 2024-09-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_calendar', '0003_rename_criado_em_commitment_criated_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='title',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='date_time_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='commitment',
            old_name='date_time_start',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='criated_in',
        ),
        migrations.AddField(
            model_name='commitment',
            name='processes',
            field=models.CharField(default='My default process', max_length=200),
        ),
    ]
